### ISSUE TITLE
"/me gives" is not recognized

### ISSUE THREAD

**Issue by mccoyst** [velour/catbase#16] opened 2016-03-12 00:06 UTC
Catbase probably sees it in a different form that the IRC weirdo thing. (Or it might not see it at all, given that it seemingly can't send them.)

**Comment by chrissexton** [comment] 2016-03-12 23:27
An inventory system does not exist right yet, should be a pretty simple addition to write once the other stuff is taken care of. I'd think just some table that tracks item and owner ought to be enough.

**Comment by chrissexton** [comment] 2016-03-13 13:49
Oh hey, this is a duplicate of #2.

**Closed by chrissexton** 2016-03-13 13:49 UTC
Labels: enhancement
